#cloud-config
users:
  - default
  - name: tgproxy
package_upgrade: true
packages:
  - python3
  - python3-uvloop 
  - python3-cryptography
  - python3-socks 
  - libcap2-bin 
  - ca-certificates
  - curl
  - wget
  - gnupg-agent
  - software-properties-common
  - git
runcmd:
  # install docker following the guide: https://docs.docker.com/install/linux/docker-ce/ubuntu/
  - cd /opt/
  - git clone https://github.com/alexbers/mtprotoproxy 
  - cd  mtprotoproxy
  - sed -i 's/00000000000000000000000000000001/751F2F753854422EA4C5FDDB8314F068/g' config.py
  - echo 'TLS_DOMAIN = "www.googleapis.com"'>> config.py
  - wget https://raw.githubusercontent.com/Antyfilter/AntyProxy/main/telegram/mtproxy.service
  - sudo mv mtproxy.service /etc/systemd/system/
  - sudo systemctl enable mtproxy.service
  - sudo systemctl start mtproxy.service
power_state:
  mode: reboot
  message: Restarting after installing
